version: '3.2'

services:
  client:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        - WITH_XDEBUG=true
    working_dir: /opt/project
    expose:
      - 9000
    environment:
      - XDEBUG_MODE=coverage
  client-80:
    build:
      context: ../
      dockerfile: docker/Dockerfile-php-8.0
      args:
        - WITH_XDEBUG=false
    working_dir: /opt/project
  client-74:
    build:
      context: ../
      dockerfile: docker/Dockerfile-php-7.4
      args:
        - WITH_XDEBUG=false
    working_dir: /opt/project